#!/usr/bin/env python3
import json
import time
import urllib.request
from pathlib import Path

from artwork_region_policy import validate_artwork_region

ROOT = Path(__file__).resolve().parents[1]
TARGETS = ROOT / "data" / "artwork-curated-url-targets.json"
GAMES = ROOT / "data" / "artwork-games.json"
MISSING = ROOT / "data" / "artwork-missing.json"
MANIFEST = ROOT / "public" / "covers" / "manifest.json"
MODULE = ROOT / "src" / "data" / "game-artwork.ts"
REPORT = ROOT / "data" / "artwork-curated-url-report.json"
COVERS = ROOT / "public" / "covers"

def load(path, fallback):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return fallback

def download(url, dest, referer):
    req = urllib.request.Request(url, headers={
        "User-Agent":"MarioRetroCollection/1.0",
        "Referer":referer,
        "Accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"
    })
    with urllib.request.urlopen(req, timeout=90) as response:
        dest.write_bytes(response.read())

targets=load(TARGETS,{})
games=load(GAMES,[])
missing=load(MISSING,{"entries":[]})
manifest=load(MANIFEST,{"entries":{}})
by_id={g["collectionId"]:g for g in games}
missing_ids={e["collectionId"] for e in missing.get("entries",[])}

resolved={}
skipped=[]

for cid,target in targets.items():
    game=by_id.get(cid)
    if not game:
        skipped.append({"collectionId":cid,"reason":"not-current-game"})
        continue
    if cid not in missing_ids:
        if not target.get("replaceExisting"):
            skipped.append({"collectionId":cid,"reason":"already-resolved"})
            continue
        if cid not in manifest.get("entries", {}):
            raise RuntimeError(f"{cid}: replaceExisting requires a current manifest entry")
    if game.get("platform") != target.get("platform"):
        raise RuntimeError(f"{cid}: platform mismatch")
    try:
        validate_artwork_region(
            target.get("region"),
            game.get("region"),
            game.get("artworkPolicy"),
        )
    except ValueError as error:
        raise RuntimeError(f"{cid}: {error}") from error

    ext=".jpg"
    dest=COVERS / f"{cid}{ext}"
    COVERS.mkdir(parents=True, exist_ok=True)
    download(target["sourceImage"], dest, target["sourcePage"])

    resolved[cid]={
        "file":f"/covers/{cid}{ext}",
        "source":"curated-exact-url",
        "serial":target.get("serial"),
        "productCode":game.get("productCode"),
        "regionName":target.get("region"),
        "artworkVariant":target.get("artworkVariant"),
        "mediaType":target.get("type","cover"),
        "matchedBy":"manual-exact-title-platform-region",
        "sourcePage":target["sourcePage"],
        "sourceImage":target["sourceImage"],
        "matchScore":1200
    }

entries=dict(manifest.get("entries",{}))
entries.update(resolved)
entries=dict(sorted(entries.items()))

manifest.update({
    "generatedAt":time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "source":"local-artwork",
    "entries":entries,
    "matched":len(entries),
    "missing":max(0,len(games)-len(entries)),
})

remaining=[e for e in missing.get("entries",[]) if e.get("collectionId") not in resolved]
out_missing=dict(missing)
out_missing["generatedAt"]=manifest["generatedAt"]
out_missing["matched"]=len(entries)
out_missing["missing"]=len(remaining)
out_missing["entries"]=remaining

MANIFEST.write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
MISSING.write_text(json.dumps(out_missing,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
MODULE.write_text("// Generated by the artwork importers. Do not edit by hand.\nexport const GAME_ARTWORK: Record<string, string> = "+json.dumps({cid:e["file"] for cid,e in entries.items()},indent=2,ensure_ascii=False)+";\n",encoding="utf-8")
REPORT.write_text(json.dumps({
    "generatedAt":manifest["generatedAt"],
    "resolved":len(resolved),
    "remaining":len(remaining),
    "entries":resolved,
    "skipped":skipped
},indent=2,ensure_ascii=False)+"\n",encoding="utf-8")

print(f"Curated exact artwork added: {len(resolved)}")
print(f"Remaining without artwork: {len(remaining)}")
